(function(A){
  const U=A.Utils,C=A.CONFIG;
  class Application{
    constructor(){
      this.ui=new A.UIManager();this.map=new A.MapManager();this.grid=new A.GridRepository();
      this.state={selectedTime:new Date(),smokeVariable:'pm10_wildfires',smokeData:[],wildfireSummaryData:[],fireData:[],fireEvents:[],fireImpacts:[],windData:[],windEnabled:false,windLevel:'10m',fwiEnabled:false,firesEnabled:true,heatEnabled:false,impactEnabled:true,downwindEnabled:true,smokePoints:false,gridMaster:true,selectedPoint:null,frpThreshold:50,firePolygonsEnabled:false,firePolygonData:null};
      this.controllers={air:null,wind:null,firms:null,detail:null,firePolygon:null};this.reqSeq={air:0,wind:0,firms:0,detail:0,firePolygon:0};this.moveTimer=null;this.timeTimer=null;this.playTimer=null;this.lastApiCall=0;
    }
    async init(){
      this.ui.init();this.map.init(p=>this.selectPoint(p));this.bindUI();this.restoreSettings();this.ui.setTime(this.state.selectedTime);this.ui.setUpdated();
      A.Events.on('focusRisk',a=>{if(!a?.event)return;this.map.setView(a.event.lat,a.event.lon,10);this.selectPoint({lat:a.event.lat,lon:a.event.lon,fire:a.event.representative,fireEvent:a.event});});A.Events.on('basemapStatus',x=>A.Events.emit('service',{id:'basemap',state:'ok',note:`${x.key} · ${x.mode==='proxy'?'yerel tile proxy':'doğrudan tile'}`}));A.Events.on('basemapError',x=>{A.Events.emit('service',{id:'basemap',state:'error',note:x.note||'Altlık tile hatası'});this.ui.toast(x.note||'Harita altlığı yüklenemedi; OSM altlığına geçiliyor.','warn');});A.Events.on('outsideDataRegion',()=>this.ui.toast('Haritada serbestçe gezebilirsiniz; yangın/duman/meteoroloji veri sorguları yalnız Türkiye veri alanında çalışır.','warn'));
      this.grid.loadCore().then(()=>{this.updateImpact();this.toggleGridMaster(true);}).catch(e=>this.ui.toast(`Şebeke core veri yüklenemedi: ${e.message}. start_windows.bat / localhost kullanın.`,'error'));
      this.healthCheck(false);this.loadSmokeGrid();this.loadWindGrid(true);
      if(A.CONFIG.firmsMapKey&&A.CONFIG.firmsMapKey!=='__FIRMS_MAP_KEY__')this.loadFirms();else A.Events.emit('service',{id:'firms',state:'warn',note:'MAP_KEY eksik; FIRMS katmanı pasif'});
      this.map.map.on('moveend',()=>{clearTimeout(this.moveTimer);this.moveTimer=setTimeout(()=>{const now=Date.now();if(now-this.lastApiCall<4000)return;this.lastApiCall=now;this.loadSmokeGrid();setTimeout(()=>this.loadWindGrid(true),600);},2000);});
    }
    restoreSettings(){
      document.getElementById('firmsSource').value=A.FirmsAdapter.source();
      const wl=localStorage.getItem('windLevel');if(C.windLevels[wl])this.state.windLevel=wl;document.getElementById('windLevel').value=this.state.windLevel;document.getElementById('baseMapSelect').value=this.map.baseKey||'satellite';
      document.getElementById('frpThreshold').value=this.state.frpThreshold;document.getElementById('frpThresholdValue').textContent=`≥${this.state.frpThreshold} MW`;this.map.frpThreshold=this.state.frpThreshold;const cel=document.getElementById('frpCount');if(cel)cel.textContent='— olay gösteriliyor';
    }
    bindUI(){
      document.getElementById('closeDetailBtn').addEventListener('click',()=>{this.ui.closeDetail();this.map.clearWindVector();});
      document.getElementById('baseMapSelect').addEventListener('change',e=>this.map.setBaseMap(e.target.value));
      document.getElementById('layerFires').addEventListener('change',e=>{this.state.firesEnabled=e.target.checked;this.map.toggleFires(e.target.checked);});
      document.getElementById('layerFrpHeat').addEventListener('change',e=>{this.state.heatEnabled=e.target.checked;this.map.toggleHeat(e.target.checked);});
      document.getElementById('frpThreshold').addEventListener('input',e=>{const v=Number(e.target.value);this.state.frpThreshold=v;document.getElementById('frpThresholdValue').textContent=`≥${v} MW`;this.map.frpThreshold=v;this.map.renderFires(this.state.selectedTime);this.state.fireEvents=this.map.fireEventsVisible;this.updateImpact();const el=document.getElementById('frpCount');if(el)el.textContent=`${this.state.fireEvents.length.toLocaleString('tr-TR')} olay gösteriliyor`;});
      document.getElementById('layerFireGridImpact').addEventListener('change',e=>{this.state.impactEnabled=e.target.checked;this.map.setFireImpacts(this.state.fireImpacts,e.target.checked);});
      document.getElementById('layerDownwindCorridor').addEventListener('change',e=>{this.state.downwindEnabled=e.target.checked;if(e.target.checked)this.loadWindGrid(true);else this.map.setDownwindCorridors([],false);});
      document.getElementById('layerFirePolygons').addEventListener('change',e=>{this.state.firePolygonsEnabled=e.target.checked;if(e.target.checked){if(!this.state.firePolygonData)this.loadFirePolygons();else this.map.setFirePolygons(this.state.firePolygonData,true);}else this.map.setFirePolygons(null,false);});
      document.querySelectorAll('.smokeLayer').forEach(el=>el.addEventListener('change',e=>{if(e.target.checked){this.state.smokeVariable=e.target.dataset.var;this.loadSmokeGrid();}}));
      document.getElementById('layerSmokePoints').addEventListener('change',e=>{this.state.smokePoints=e.target.checked;this.map.showSmokePoints(e.target.checked);});
      document.getElementById('smokeOpacity').addEventListener('input',e=>{const v=Number(e.target.value);this.map.smokeLayer?.setOpacity(v);document.getElementById('smokeOpacityValue').textContent=`%${Math.round(v*100)}`;});
      document.getElementById('clearSmokeLayer').addEventListener('click',()=>{document.querySelectorAll('.smokeLayer').forEach(x=>x.checked=false);this.state.smokeVariable=null;this.state.smokeData=[];this.map.clearSmoke();this.ui.renderExportSummary(this.state);});
      document.getElementById('layerWind').addEventListener('change',e=>{this.state.windEnabled=e.target.checked;this.map.toggleWind(e.target.checked);if(e.target.checked)this.loadWindGrid(true);});
      document.getElementById('windLevel').addEventListener('change',e=>{this.state.windLevel=e.target.value;localStorage.setItem('windLevel',this.state.windLevel);this.loadWindGrid(true);if(this.state.selectedPoint)this.selectPoint(this.state.selectedPoint,true);});
      document.getElementById('layerFwi').addEventListener('change',e=>{this.state.fwiEnabled=e.target.checked;this.map.toggleFwi(e.target.checked,this.state.selectedTime);});
      document.getElementById('layerGridMaster').addEventListener('change',e=>this.toggleGridMaster(e.target.checked));document.querySelectorAll('.gridLayer').forEach(el=>el.addEventListener('change',()=>{if(this.state.gridMaster)this.refreshGridLayers();}));
      document.getElementById('timeSlider').addEventListener('input',e=>this.setTimeOffset(Number(e.target.value),false));document.getElementById('timeSlider').addEventListener('change',()=>this.scheduleTimeReload(0));
      document.getElementById('nowBtn').addEventListener('click',()=>{document.getElementById('timeSlider').value='0';this.setTimeOffset(0,true);});document.getElementById('stepBackBtn').addEventListener('click',()=>this.shiftTime(-3));document.getElementById('stepForwardBtn').addEventListener('click',()=>this.shiftTime(3));document.getElementById('playBtn').addEventListener('click',()=>this.togglePlay());
      document.getElementById('citySearchBtn').addEventListener('click',()=>this.searchCity());document.getElementById('citySearch').addEventListener('keydown',e=>{if(e.key==='Enter')this.searchCity();});
      document.getElementById('firmsSource').addEventListener('change',e=>{A.FirmsAdapter.setSource(e.target.value);A.Cache.clear('firms:');this.loadFirms();});
      document.getElementById('atmoHubDiscoverBtn').addEventListener('click',()=>this.discoverAtmoHub());document.getElementById('healthCheckBtn').addEventListener('click',()=>this.healthCheck(true));
      document.getElementById('refreshAllBtn').addEventListener('click',()=>{A.Cache.clear();this.loadSmokeGrid();this.loadWindGrid(true);if(C.firmsMapKey&&C.firmsMapKey!=='__FIRMS_MAP_KEY__')this.loadFirms();this.ui.toast('Önbellek temizlendi; gerçek kaynaklar yeniden isteniyor.');});
      document.getElementById('exportCsvBtn').addEventListener('click',()=>A.ExportManager.csv(this.state));document.getElementById('exportJsonBtn').addEventListener('click',()=>A.ExportManager.json(this.state));document.getElementById('exportGeoJsonBtn').addEventListener('click',()=>A.ExportManager.geojson(this.state));
    }
    async toggleGridMaster(show){this.state.gridMaster=show;document.getElementById('gridSublayers').classList.toggle('disabledBlock',!show);if(!show){this.map.hideAllGrid();return;}await this.refreshGridLayers();}
    async refreshGridLayers(){const selected=new Set([...document.querySelectorAll('.gridLayer:checked')].map(x=>x.dataset.grid));for(const key of Object.keys(C.gridSources)){try{if(selected.has(key)){const data=await this.grid.loadGroup(key);await this.map.setGridGroup(key,data,true);}else if(this.map.gridLayers.has(key)){await this.map.setGridGroup(key,this.grid.data.get(key),false);}}catch(e){this.ui.toast(`Şebeke katmanı ${key}: ${e.message}`,'error');}}}
    setTimeOffset(hours,reload){const d=new Date(Date.now()+hours*3600e3);d.setUTCMinutes(0,0,0);this.state.selectedTime=d;this.ui.setTime(d);this.map.renderFires(d);this.state.fireEvents=this.map.fireEventsVisible;if(this.state.heatEnabled)this.map.toggleHeat(true);if(this.state.fwiEnabled)this.map.toggleFwi(true,d);this.updateImpact();this.ui.renderExportSummary(this.state);if(reload)this.scheduleTimeReload(0);else this.scheduleTimeReload(300);}
    shiftTime(delta){const s=document.getElementById('timeSlider'),v=U.clamp(Number(s.value)+delta,Number(s.min),Number(s.max));s.value=String(v);this.setTimeOffset(v,true);}
    togglePlay(){const b=document.getElementById('playBtn');if(this.playTimer){clearInterval(this.playTimer);this.playTimer=null;b.textContent='▶';return;}b.textContent='⏸';this.playTimer=setInterval(()=>{const s=document.getElementById('timeSlider');let v=Number(s.value)+C.timeline.playStepHours;if(v>Number(s.max))v=Number(s.min);s.value=String(v);this.setTimeOffset(v,true);},C.timeline.playIntervalMs);}
    scheduleTimeReload(ms){clearTimeout(this.timeTimer);this.timeTimer=setTimeout(()=>{this.loadSmokeGrid();this.loadWindGrid(true);if(this.state.selectedPoint)this.selectPoint(this.state.selectedPoint,true);},ms);}
    async loadSmokeGrid(){
      if(!this.state.smokeVariable)return;this.controllers.air?.abort();const ctrl=new AbortController();this.controllers.air=ctrl;const seq=++this.reqSeq.air,pts=U.adaptiveGrid(this.map.bounds(),this.map.zoom(),120),variable=this.state.smokeVariable;
      if(!pts.length){this.state.smokeData=[];this.state.wildfireSummaryData=[];this.map.clearSmoke();this.ui.setNearestNote('Harita Türkiye veri alanının dışında. Harita serbesttir; CAMS duman sorgusu yalnız Türkiye ile kesişen görünümde yapılır.');this.ui.updateEnvironmentalKpis([],this.state.windData);return;}
      try{let selected,wf;if(variable==='pm10_wildfires'){selected=await A.OpenMeteoAir.grid(pts,variable,this.state.selectedTime,ctrl.signal);wf=selected;}else{[selected,wf]=await Promise.all([A.OpenMeteoAir.grid(pts,variable,this.state.selectedTime,ctrl.signal),A.OpenMeteoAir.grid(pts,'pm10_wildfires',this.state.selectedTime,ctrl.signal)]);}if(seq!==this.reqSeq.air)return;this.state.smokeData=selected;this.state.wildfireSummaryData=wf;this.map.setSmoke(selected,variable,this.state.smokePoints);const nearest=selected.find(x=>x.validAt)?.validAt;this.ui.setNearestNote(nearest?`CAMS/Open-Meteo model zamanı: ${U.formatUtc(new Date(nearest))} · Türkiye ile kesişen viewport · ${selected.length} örnek nokta`:'Duman/aerosol için model verisi bulunamadı.');this.ui.updateEnvironmentalKpis(this.state.wildfireSummaryData,this.state.windData);this.ui.renderExportSummary(this.state);this.ui.setUpdated();}catch(e){if(e.kind!=='ABORTED')this.ui.toast(`Duman/aerosol katmanı: ${e.kind||e.message}`,'error');}
    }
    async loadWindGrid(force=false){
      if(!force&&!this.state.windEnabled&&!this.state.downwindEnabled)return;this.controllers.wind?.abort();const ctrl=new AbortController();this.controllers.wind=ctrl;const seq=++this.reqSeq.wind,pts=U.adaptiveGrid(this.map.bounds(),Math.max(2,this.map.zoom()-1),60);
      if(!pts.length){this.state.windData=[];this.map.setWind([],this.state.windLevel);this.updateImpact();this.ui.updateEnvironmentalKpis(this.state.wildfireSummaryData,[]);return;}
      try{const data=await A.OpenMeteoWeather.grid(pts,this.state.selectedTime,this.state.windLevel,ctrl.signal);if(seq!==this.reqSeq.wind)return;this.state.windData=data;this.map.setWind(data,this.state.windLevel);this.map.toggleWind(this.state.windEnabled);this.updateImpact();this.ui.updateEnvironmentalKpis(this.state.wildfireSummaryData,this.state.windData);this.ui.renderExportSummary(this.state);}catch(e){if(e.kind!=='ABORTED')this.ui.toast(`Rüzgâr katmanı: ${e.kind||e.message}`,'error');}
    }
    async loadFirms(){
      this.controllers.firms?.abort();const ctrl=new AbortController();this.controllers.firms=ctrl;const seq=++this.reqSeq.firms;try{const data=await A.FirmsAdapter.load(ctrl.signal);if(seq!==this.reqSeq.firms)return;this.state.fireData=data;this.map.setFires(data,this.state.selectedTime);this.map.toggleFires(this.state.firesEnabled);this.state.fireEvents=this.map.fireEventsVisible;if(this.state.heatEnabled)this.map.toggleHeat(true);this.updateImpact();this.ui.renderExportSummary(this.state);this.ui.setUpdated();}catch(e){if(e.kind==='ABORTED')return;if(e.kind==='AUTH_REQUIRED'){document.getElementById('kpiFireEvents').textContent='KEY';document.getElementById('kpiDetectionsNote').textContent='NASA FIRMS MAP_KEY eksik';this.ui.toast('GitHub Secret\'a FIRMS_MAP_KEY ekleyin.','warn');return;}this.ui.toast(`FIRMS: ${e.kind||e.message}`,'warn');}
    }
    async loadFirePolygons(){
      this.controllers.firePolygon?.abort();const ctrl=new AbortController();this.controllers.firePolygon=ctrl;const seq=++this.reqSeq.firePolygon;
      try{const fc=await A.FirePolygonAdapter.load(ctrl.signal);if(seq!==this.reqSeq.firePolygon)return;this.state.firePolygonData=fc;this.map.setFirePolygons(fc,this.state.firePolygonsEnabled);}catch(e){if(e.kind!=='ABORTED')this.ui.toast(`Yangın alanı katmanı: ${e.kind||e.message}`,'error');}
    }
    updateImpact(){if(!this.grid.loadedCore)return;this.state.fireEvents=this.map.fireEventsVisible||[];this.state.fireImpacts=this.grid.analyzeEvents(this.state.fireEvents,25,this.state.selectedTime,this.state.windData);this.map.setFireImpacts(this.state.fireImpacts,this.state.impactEnabled);this.map.setDownwindCorridors(this.state.fireImpacts,this.state.downwindEnabled);this.ui.renderImpact(this.state.fireImpacts);this.ui.renderExportSummary(this.state);}
    async selectPoint(p,silent=false){
      if(!U.insideRegion(p)){if(!silent)this.ui.openDetail('Türkiye veri alanı dışında','<div class="warningBox">Harita dünya üzerinde serbestçe gezilebilir. Ancak FIRMS, CAMS/Open-Meteo ve şebeke etki sorguları yalnız Türkiye veri alanında çalışır; bu koordinat için veri isteği yapılmadı.</div>');return;}
      p={...p,lat:Number(p.lat),lon:Number(p.lon)};this.state.selectedPoint={lat:p.lat,lon:p.lon,fire:p.fire,fireEvent:p.fireEvent,gridFeature:p.gridFeature};this.controllers.detail?.abort();const ctrl=new AbortController();this.controllers.detail=ctrl;const seq=++this.reqSeq.detail;if(!silent)this.ui.openDetail(p.fireEvent?'Yangın olayı':p.fire?'FIRMS termal tespiti':p.gridFeature?'Şebeke varlığı':'Konum sorgulanıyor…','<div class="emptyState">CAMS wildfire PM10, meteoroloji ve şebeke yakınlığı sorgulanıyor…</div>');
      try{if(!this.grid.loadedCore)await this.grid.loadCore();const [air,weather]=await Promise.all([A.OpenMeteoAir.detail(p,this.state.selectedTime,ctrl.signal),A.OpenMeteoWeather.detail(p,this.state.selectedTime,ctrl.signal)]);if(seq!==this.reqSeq.detail)return;const end=Math.min(this.state.selectedTime.getTime(),Date.now()+15*60e3),start=end-24*3600e3,nearby=(this.state.fireData||[]).filter(f=>{const t=Date.parse(f.detectedAt);return t>=start&&t<=end;}).map(f=>({fire:f,distance:U.haversineKm({lat:p.lat,lon:p.lon},{lat:f.lat,lon:f.lon})})).filter(x=>x.distance<=100).sort((a,b)=>a.distance-b.distance),nearest=this.grid.nearest({lat:p.lat,lon:p.lon},50);this.ui.renderPointDetail(p,air,weather,nearby,p.fire,p.fireEvent,p.gridFeature,nearest);const lvl=C.windLevels[this.state.windLevel]||C.windLevels['10m'];this.map.drawWindVector({lat:p.lat,lon:p.lon},weather.values[lvl.direction],weather.values[lvl.speed],this.state.windLevel);this.ui.renderExportSummary(this.state);}catch(e){if(e.kind!=='ABORTED')this.ui.openDetail('Veri alınamadı',`<div class="warningBox">${U.escapeHtml(e.kind||e.message)}. Ayarlar → Veri Kaynağı Durumu bölümünü kontrol edin.</div>`);}
    }
    async searchCity(){const q=document.getElementById('citySearch').value.trim(),box=document.getElementById('searchResults');if(q.length<2)return;box.classList.remove('hidden');box.innerHTML='<div class="searchItem">Türkiye içinde aranıyor…</div>';try{const results=await A.Geocoder.search(q);if(!results.length){box.innerHTML='<div class="searchItem">Türkiye içinde sonuç yok.</div>';return;}box.innerHTML=results.map((r,i)=>`<div class="searchItem" data-i="${i}"><strong>${U.escapeHtml(r.name)}</strong><br><small>${U.escapeHtml([r.admin1,r.country].filter(Boolean).join(', '))}</small></div>`).join('');box.querySelectorAll('.searchItem[data-i]').forEach(el=>el.addEventListener('click',()=>{const r=results[Number(el.dataset.i)];box.classList.add('hidden');this.map.setView(r.latitude,r.longitude,10);this.selectPoint({lat:r.latitude,lon:r.longitude});}));}catch(e){box.innerHTML=`<div class="searchItem">Arama hatası: ${U.escapeHtml(e.kind||e.message)}</div>`;}}
    async discoverAtmoHub(){const box=document.getElementById('atmoHubDiscoveryResult');box.innerHTML='<strong>AtmoHub canlı keşfi çalışıyor…</strong><br><small>Ana portal + tematik sayfalar + JS/CSS bundle varlıkları taranıyor. Bu işlem 10–40 saniye sürebilir.</small>';const r=await A.AtmoHubAdapter.discoverCapabilities(true);this.ui.renderAtmoHubDiscovery(r);}
    async healthCheck(showToast=true){      A.Events.emit('service',{id:'grid',state:this.grid.loadedCore?'ok':'idle',note:this.grid.loadedCore?'Core grid hazır':'Yerel GeoJSON yükleniyor'});if(!C.firmsMapKey||C.firmsMapKey==='__FIRMS_MAP_KEY__')A.Events.emit('service',{id:'firms',state:'warn',note:'MAP_KEY eksik; servis çağrısı yapılmadı'});A.Events.emit('service',{id:'atmohub',state:'warn',note:'Public API yalnız Ayarlar → AtmoHub keşfi ile doğrulanır; CAMS fallback aktif'});const ctrl=new AbortController();await Promise.allSettled([A.OpenMeteoAir.health(ctrl.signal),A.OpenMeteoWeather.health(ctrl.signal)]);A.Events.emit('service',{id:'effis',state:'idle',note:'Resmî WMS; FWI açıldığında tile isteği doğrulanır'});if(showToast)this.ui.toast('Bağlantı kontrolü tamamlandı. Mock veri kullanılmadı.');}
  }
  A.app=new Application();window.addEventListener('DOMContentLoaded',()=>A.app.init());
})(window.AtmoApp);
