(function(A){
  const U=A.Utils,C=A.CONFIG;
  class UIManager{
    constructor(){this.services={basemap:{name:'Harita Altlığı',state:'idle'},atmohub:{name:'AtmoHub',state:'idle'},firms:{name:'NASA FIRMS',state:'idle'},air:{name:'CAMS Wildfire PM10',state:'idle'},effis:{name:'Copernicus EFFIS FWI',state:'idle'},effisBurntArea:{name:'EFFIS Yanmış Alan',state:'idle'},gfw:{name:'GFW Orman Bozulma',state:'idle'},mtg:{name:'EUMETSAT MTG',state:'idle'},weather:{name:'Open-Meteo Weather',state:'idle'},grid:{name:'OSM İletim Şebekesi',state:'idle'},geocode:{name:'Geocoding',state:'idle'}};this.chart=null;this.sortKey=null;this.sortDir=1;}
    init(){
      document.querySelectorAll('.navBtn').forEach(b=>b.addEventListener('click',()=>this.showView(b.dataset.view)));document.querySelector('.collapseBtn')?.addEventListener('click',e=>{const body=document.getElementById('layerPanelBody');body.classList.toggle('hidden');e.currentTarget.textContent=body.classList.contains('hidden')?'+':'−';if(document.getElementById('view-map')?.classList.contains('active'))setTimeout(()=>A.app?.map?.map?.invalidateSize(),30);});
      document.getElementById('legendToggleBtn')?.addEventListener('click',e=>{const stack=document.getElementById('legendStack'),hidden=stack.classList.toggle('legendsHidden');e.currentTarget.textContent=hidden?'◫ Lejantları Göster':'◫ Lejantları Gizle';});
      A.Events.on('service',s=>this.updateService(s));A.Events.on('firesRendered',x=>{document.getElementById('kpiFireEvents').textContent=(x.events??0).toLocaleString('tr-TR');document.getElementById('kpiDetectionsNote').textContent=`${(x.detections??0).toLocaleString('tr-TR')} termal tespit · 5 km/6 saat küme`;const el=document.getElementById('frpCount');if(el)el.textContent=`${(x.events??0).toLocaleString('tr-TR')} / ${(x.eventsTotal??x.events??0).toLocaleString('tr-TR')} olay gösteriliyor`;});A.Events.on('gridCoreReady',s=>this.renderGridSummary(s));this.renderServices();
      document.querySelectorAll('#impactTable th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.sort;if(this.sortKey===key)this.sortDir*=-1;else{this.sortKey=key;this.sortDir=1;}if(A.app?.state?.fireImpacts)this.renderImpact(A.app.state.fireImpacts);}));
    }
    showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='map')setTimeout(()=>A.app?.map?.map?.invalidateSize(),30);}
    toast(msg,type='info'){const h=document.getElementById('toastHost'),d=document.createElement('div');d.className=`toast ${type}`;d.textContent=msg;h.appendChild(d);setTimeout(()=>d.remove(),5000);}
    updateService(s){const current=this.services[s.id]||{name:s.id};this.services[s.id]={...current,...s,last:s.state==='ok'?new Date():current.last};this.renderServices();}
    renderServices(){const body=document.getElementById('serviceStatusBody');if(!body)return;body.innerHTML=Object.entries(this.services).map(([,s])=>{const cls=s.state==='ok'?'status-ok':s.state==='error'?'status-bad':s.state==='warn'?'status-warn':'status-idle',label=s.state==='ok'?'Bağlı':s.state==='error'?'Hata':s.state==='warn'?'Sınırlı / bekliyor':'Bekliyor';return `<tr><td>${U.escapeHtml(s.name)}</td><td><span class="statusDot ${cls}"></span>${label}</td><td>${s.last?U.formatLocal(s.last):'—'}</td><td>${s.latency!=null?(s.latency===0?'cache':s.latency+' ms'):'—'}</td><td>${s.count==null?'—':s.count}</td><td>${U.escapeHtml(s.note||'')}</td></tr>`;}).join('');}
    setTime(date){document.getElementById('selectedTimeLocal').textContent=U.formatLocal(date);document.getElementById('selectedTimeUtc').textContent=U.formatUtc(date);}
    setNearestNote(t){document.getElementById('nearestTimeNote').textContent=t||'FIRMS gözlem zamanı ile model tahmin zamanı ayrı tutulur.';}
    setUpdated(){document.getElementById('lastUpdated').textContent='Son güncelleme: '+U.formatLocal(new Date());}
    updateEnvironmentalKpis(wildfireData,windData){
      const wf=(wildfireData||[]).map(x=>x.value).filter(Number.isFinite),w=(windData||[]).filter(x=>Number.isFinite(x.speed));const wfEl=document.getElementById('kpiWildfirePm10'),windEl=document.getElementById('kpiWind');
      if(wf.length){const max=Math.max(...wf);wfEl.textContent=`${U.round(max,1)} µg/m³`;wfEl.classList.toggle('zeroValue',max===0);wfEl.parentElement.querySelector('small').textContent=max===0?'CAMS: bu grid/zamanda yangın katkısı 0':'CAMS Europe · viewport maksimumu';}else wfEl.textContent='—';
      if(w.length){const max=w.reduce((a,b)=>b.speed>a.speed?b:a,w[0]);windEl.textContent=`${U.round(max.speed,1)} km/h`;windEl.parentElement.querySelector('small').textContent=`${C.windLevels[max.level]?.label||max.level} · ${Math.round(max.direction)}° ${U.cardinal(max.direction)}`;}else windEl.textContent='—';
    }
    openDetail(title,html){document.getElementById('detailTitle').textContent=title;document.getElementById('detailContent').innerHTML=html;document.getElementById('detailPanel').classList.add('open');}
    closeDetail(){document.getElementById('detailPanel').classList.remove('open');}
    val(v,d=1,suffix=''){return v!=null&&Number.isFinite(Number(v))?U.round(Number(v),d)+suffix:'—';}
    renderPointDetail(point,air,weather,nearbyFires,fire,fireEvent,gridFeature,nearest){
      const v=air?.values||{},w=weather?.values||{},gf=gridFeature?.properties||{};let title=fireEvent?`Yangın olayı · ${fireEvent.count} tespit`:fire?`FIRMS · ${fire.product}`:gridFeature?(gridFeature.kind==='substation'?'Trafo Merkezi':'İletim Hattı'):`${point.lat.toFixed(4)}, ${point.lon.toFixed(4)}`;
      const nearestLine=nearest?.line,nearestSub=nearest?.substation,closest=Math.min(nearestLine?.distanceKm??Infinity,nearestSub?.distanceKm??Infinity),band=Number.isFinite(closest)?U.impactBand(closest):null;
      const gridBlock=gridFeature?`<div class="detailSection"><h3>⚡ Seçili şebeke varlığı</h3><div class="metricGrid"><div class="metric"><small>Tür</small><strong>${gridFeature.kind==='substation'?'Trafo merkezi':'Havai/OSM power line'}</strong></div><div class="metric"><small>Gerilim</small><strong>${U.escapeHtml(gf.voltage||gf.voltageGroup||'Bilinmiyor')}</strong></div><div class="metric"><small>Ad</small><strong>${U.escapeHtml(gf.name||'Adsız')}</strong></div><div class="metric"><small>Operatör</small><strong>${U.escapeHtml(gf.operator||'—')}</strong></div></div><div class="sourceNote">Kaynak: OpenStreetMap power-grid dışa aktarımı · ODbL</div></div>`:'';
      const eventBlock=fireEvent?`<div class="detailSection"><h3>🔥 Kümelenmiş yangın olayı</h3><div class="metricGrid"><div class="metric"><small>Termal tespit</small><strong>${fireEvent.count}</strong></div><div class="metric"><small>Maks. FRP</small><strong>${this.val(fireEvent.maxFrp,1,' MW')}</strong></div><div class="metric"><small>Son tespit</small><strong>${U.formatLocal(new Date(fireEvent.latestDetectedAt))}</strong></div><div class="metric"><small>İlk tespit</small><strong>${U.formatLocal(new Date(fireEvent.earliestDetectedAt))}</strong></div></div><div class="sourceNote">5 km / 6 saat uzamsal-zamansal küme; gerçek yangın perimetresi değildir.</div></div>`:'';
      const fireBlock=fire&&!fireEvent?`<div class="detailSection"><h3>🔥 Uydu termal tespiti</h3><div class="metricGrid"><div class="metric"><small>Tespit</small><strong>${U.formatLocal(new Date(fire.detectedAt))}</strong></div><div class="metric"><small>FRP</small><strong>${this.val(fire.frp,1,' MW')}</strong></div><div class="metric"><small>Uydu / sensör</small><strong>${U.escapeHtml(fire.satellite||'—')} / ${U.escapeHtml(fire.sensor||'—')}</strong></div><div class="metric"><small>Confidence</small><strong>${U.escapeHtml(fire.confidence||'—')}</strong></div></div><div class="sourceNote">FIRMS hotspot = termal anomali; yangın perimetresi değildir.</div></div>`:'';
      const proximity=`<div class="detailSection"><h3>⚡ Şebeke yakınlık taraması</h3><div class="metricGrid"><div class="metric"><small>En yakın hat</small><strong>${nearestLine?this.val(nearestLine.distanceKm,2,' km'):'>50 km / yok'}</strong></div><div class="metric"><small>Hat gerilimi</small><strong>${nearestLine?U.escapeHtml(nearestLine.feature.props?.voltage||nearestLine.feature.props?.voltageGroup||'bilinmiyor'):'—'}</strong></div><div class="metric"><small>En yakın TM</small><strong>${nearestSub?this.val(nearestSub.distanceKm,2,' km'):'>50 km / yok'}</strong></div><div class="metric"><small>Mesafe bandı</small><strong class="riskText ${band?.level||'low'}">${band?.label||'Düşük yakınlık'}</strong></div><div class="metric"><small>Yakın OSM segmenti</small><strong>${nearestLine?this.val(U.haversineKm(nearestLine.feature.a,nearestLine.feature.b),2,' km'):'—'}</strong></div></div><div class="sourceNote">1/3/10/25 km bantları uygulama içi önceliklendirme içindir; resmî güvenlik mesafesi değildir. Segment uzunluğu yalnız en yakın OSM çizgi parçasıdır, tüm devre/hat uzunluğu değildir.</div></div>`;
      const smokeBlock=`<div class="detailSection"><h3>🌫 Yangın dumanı / aerosol · ${air?.validAt?U.formatLocal(new Date(air.validAt)):'—'}</h3><div class="metricGrid"><div class="metric"><small>Yangın kaynaklı PM10</small><strong>${this.val(v.pm10_wildfires,1,' µg/m³')}</strong></div><div class="metric"><small>Toplam PM10 içindeki pay</small><strong>${this.val(v.wildfire_share,0,'%')}</strong></div><div class="metric"><small>Model çözünürlüğü</small><strong>~11 km</strong></div><div class="metric"><small>Veri tipi</small><strong>Model tahmini</strong></div></div><div class="sourceNote">CAMS Europe via Open-Meteo. Wildfire PM10 yüzeye yakın yangın kaynaklı PM10 bileşenidir; genel PM/AQI/AOD katmanları operasyonel odağı korumak için gösterilmez.</div></div>`;
      const weatherBlock=`<div class="detailSection"><h3>💨 Meteoroloji · ${weather?.validAt?U.formatLocal(new Date(weather.validAt)):'—'}</h3><div class="metricGrid"><div class="metric"><small>10 m</small><strong>${this.val(w.wind_speed_10m,1,' km/h')} · ${w.wind_direction_10m!=null?Math.round(w.wind_direction_10m)+'° '+U.cardinal(w.wind_direction_10m):'—'}</strong></div><div class="metric"><small>850 hPa</small><strong>${this.val(w.wind_speed_850hPa,1,' km/h')} · ${w.wind_direction_850hPa!=null?Math.round(w.wind_direction_850hPa)+'°':'—'}</strong></div><div class="metric"><small>700 hPa</small><strong>${this.val(w.wind_speed_700hPa,1,' km/h')} · ${w.wind_direction_700hPa!=null?Math.round(w.wind_direction_700hPa)+'°':'—'}</strong></div><div class="metric"><small>Hamle / nem</small><strong>${this.val(w.wind_gusts_10m,1,' km/h')} / ${this.val(w.relative_humidity_2m,0,'%')}</strong></div></div><div class="sourceNote">Rüzgâr vektörü duman yörüngesi değildir; üst seviye rüzgâr taşınım bağlamı sağlar.</div></div>`;
      const fireList=`<div class="detailSection"><h3>🔥 100 km içindeki FIRMS tespitleri</h3>${nearbyFires.length?nearbyFires.slice(0,12).map(n=>`<div class="fireRow"><span>${this.val(n.distance,1,' km')} · ${this.val(n.fire.frp,1,' MW')}</span><span>${U.formatLocal(new Date(n.fire.detectedAt))}</span></div>`).join(''):'<div class="emptyState">Yüklenmiş FIRMS tespiti yok.</div>'}</div>`;
      this.openDetail(title,`<div><span class="badge ${fire||fireEvent?'observation':gridFeature?'analysis':'forecast'}">${fire||fireEvent?'UYDU GÖZLEMİ':gridFeature?'ŞEBEKE VARLIĞI':'MODEL / KONUM'}</span></div>${gridBlock}${eventBlock}${fireBlock}${proximity}${smokeBlock}${weatherBlock}${fireList}`);this.renderAnalysisSummary(point,air,weather,nearbyFires,gridFeature,nearest);this.renderChart(air?.series||[]);
    }
    renderAnalysisSummary(point,air,weather,nearby,gridFeature,nearest){const v=air?.values||{},w=weather?.values||{},nline=nearest?.line,nsub=nearest?.substation;document.getElementById('analysisPointSummary').innerHTML=`<p><strong>Koordinat:</strong> ${point.lat.toFixed(4)}, ${point.lon.toFixed(4)}</p>${gridFeature?`<p><strong>Varlık:</strong> ${U.escapeHtml(gridFeature.properties?.name||gridFeature.kind)}</p>`:''}<p><strong>Wildfire PM10:</strong> ${this.val(v.pm10_wildfires,1,' µg/m³')} (${this.val(v.wildfire_share,0,'%')})</p><p><strong>Rüzgâr 10 m:</strong> ${this.val(w.wind_speed_10m,1,' km/h')} / ${w.wind_direction_10m!=null?Math.round(w.wind_direction_10m)+'°':'—'}</p><p><strong>En yakın hat:</strong> ${nline?this.val(nline.distanceKm,2,' km'):'—'}</p><p><strong>En yakın TM:</strong> ${nsub?this.val(nsub.distanceKm,2,' km'):'—'}</p><p><strong>100 km FIRMS:</strong> ${nearby.length}</p>`;}
    renderChart(series){const canvas=document.getElementById('aqChart'),empty=document.getElementById('chartEmpty'),now=Date.now(),filtered=series.filter(x=>{const t=Date.parse(x.time);return t>=now-24*3600e3&&t<=now+48*3600e3;});if(!filtered.length||!window.Chart){canvas.style.display='none';empty.style.display='block';return;}empty.style.display='none';canvas.style.display='block';if(this.chart)this.chart.destroy();this.chart=new Chart(canvas,{type:'line',data:{labels:filtered.map(x=>U.formatLocal(new Date(x.time))),datasets:[{label:'Yangın PM10 µg/m³',data:filtered.map(x=>x.pm10_wildfires),spanGaps:true,yAxisID:'y'},{label:'Yangın PM10 payı %',data:filtered.map(x=>x.wildfire_share),spanGaps:true,yAxisID:'y1'}]},options:{responsive:true,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#cbd8e4'}}},scales:{x:{ticks:{color:'#8aa0b2',maxTicksLimit:11},grid:{color:'#172637'}},y:{position:'left',title:{display:true,text:'µg/m³',color:'#8aa0b2'},ticks:{color:'#8aa0b2'},grid:{color:'#203041'}},y1:{position:'right',min:0,max:100,title:{display:true,text:'%',color:'#8aa0b2'},ticks:{color:'#8aa0b2'},grid:{drawOnChartArea:false}}}}});}
    renderGridSummary(s){const c=s.counts||{};document.getElementById('gridSummary').innerHTML=`<p><strong>400 kV sınıfı hat:</strong> ${(c['400']||0).toLocaleString('tr-TR')}</p><p><strong>154 kV sınıfı hat:</strong> ${(c['154']||0).toLocaleString('tr-TR')}</p><p><strong>Trafo merkezi:</strong> ${(c.substations||0).toLocaleString('tr-TR')}</p><p><strong>İndekslenen hat segmenti:</strong> ${(s.segments||0).toLocaleString('tr-TR')}</p><p class="sourceNote">Risk çekirdeği 400/154 kV + TM verisini görünürlükten bağımsız kullanır.</p>`;document.getElementById('gridMetadata').innerHTML=`<p><strong>Kaynak:</strong> Kullanıcının OSM Power Grid GeoJSON'u</p><p><strong>Filtre:</strong> line/minor_line + substation</p><p><strong>Core:</strong> ${(c['400']||0)+(c['154']||0)} hat + ${c.substations||0} TM</p><p><strong>Diğer katmanlar:</strong> 20–66 kV ve gerilimi bilinmeyen hatlar isteğe bağlı lazy-load</p><p><strong>Lisans:</strong> ODbL 1.0 · © OpenStreetMap contributors</p>`;}
    renderImpact(analyses){
      const arr=analyses||[],critical=arr.filter(x=>x.riskScore>=75),high=arr.filter(x=>x.riskScore>=55&&x.riskScore<75),medium=arr.filter(x=>x.riskScore>=35&&x.riskScore<55),lineKeys=new Set(),subKeys=new Set(),downwindLineKeys=new Set(),downwindSubKeys=new Set();for(const a of arr){for(const x of a.affectedLines||[])lineKeys.add(x.key);for(const x of a.affectedSubstations||[])subKeys.add(x.key);if(a.riskScore>=35){for(const x of a.downwindAssets?.lines||[])downwindLineKeys.add(x.key);for(const x of a.downwindAssets?.substations||[])downwindSubKeys.add(x.key);}}
      document.getElementById('kpiCriticalEvents').textContent=critical.length.toLocaleString('tr-TR');document.getElementById('kpiRiskLines').textContent=lineKeys.size.toLocaleString('tr-TR');document.getElementById('kpiRiskSubstations').textContent=subKeys.size.toLocaleString('tr-TR');
      document.getElementById('impactSummary').innerHTML=`<p><strong>Kritik (75+):</strong> ${critical.length}</p><p><strong>Yüksek (55–74):</strong> ${high.length}</p><p><strong>Orta (35–54):</strong> ${medium.length}</p><p><strong>Toplam yangın olayı:</strong> ${arr.length}</p><p><strong>≤10 km benzersiz hat:</strong> ${lineKeys.size}</p><p><strong>≤10 km benzersiz TM:</strong> ${subKeys.size}</p><p><strong>Aşağı-rüzgâr koridorunda hat:</strong> ${downwindLineKeys.size}</p><p><strong>Aşağı-rüzgâr koridorunda TM:</strong> ${downwindSubKeys.size}</p><p class="sourceNote">Skor: mesafe + maksimum FRP + tespit yaşı + gerilim/TM önemi; rüzgâr grid verisi varsa doğrultu katkısı. FWI WMS sayısal skora dahil edilmez.</p>`;
      let rows=arr.filter(a=>a.minDistanceKm!=null&&a.minDistanceKm<=25).slice(0,200);
      if(this.sortKey){const d=this.sortDir;rows.sort((a,b)=>{let va,vb;switch(this.sortKey){case'riskScore':va=a.riskScore;vb=b.riskScore;break;case'count':va=a.event.count;vb=b.event.count;break;case'maxFrp':va=a.event.maxFrp;vb=b.event.maxFrp;break;case'asset':{const la=a.nearest.line,sa=a.nearest.substation,ua=la&&(!sa||la.distanceKm<=sa.distanceKm),pa=ua?la?.feature?.props?.name||la?.feature?.props?.ref:'TM';const lb=b.nearest.line,sb=b.nearest.substation,ub=lb&&(!sb||lb.distanceKm<=sb.distanceKm),pb=ub?lb?.feature?.props?.name||lb?.feature?.props?.ref:'TM';va=(pa||'Adsız').toLowerCase();vb=(pb||'Adsız').toLowerCase();break;}case'distance':{const la=a.nearest.line,sa=a.nearest.substation,ua=la&&(!sa||la.distanceKm<=sa.distanceKm);va=ua?la.distanceKm:sa?.distanceKm??Infinity;const lb=b.nearest.line,sb=b.nearest.substation,ub=lb&&(!sb||lb.distanceKm<=sb.distanceKm);vb=ub?lb.distanceKm:sb?.distanceKm??Infinity;break;}case'voltage':{const la=a.nearest.line,sa=a.nearest.substation,ua=la&&(!sa||la.distanceKm<=sa.distanceKm),pa=ua?la?.feature?.props:sa?.feature?.props;const lb=b.nearest.line,sb=b.nearest.substation,ub=lb&&(!sb||lb.distanceKm<=sb.distanceKm),pb=ub?lb?.feature?.props:sb?.feature?.props;va=(pa?.voltage||pa?.voltageGroup||'').toLowerCase();vb=(pb?.voltage||pb?.voltageGroup||'').toLowerCase();break;}case'wind':va=a.wind?a.downwindAlignment?2:1:0;vb=b.wind?b.downwindAlignment?2:1:0;break;case'latest':va=new Date(a.event.latestDetectedAt).getTime();vb=new Date(b.event.latestDetectedAt).getTime();break;default:va=0;vb=0;}if(va<vb)return-d;if(va>vb)return d;return 0;});}
      document.querySelectorAll('#impactTable th[data-sort]').forEach(th=>th.classList.toggle('sorted-asc',th.dataset.sort===this.sortKey&&this.sortDir===1));document.querySelectorAll('#impactTable th[data-sort]').forEach(th=>th.classList.toggle('sorted-desc',th.dataset.sort===this.sortKey&&this.sortDir===-1));
      const body=document.getElementById('impactTableBody');body.innerHTML=rows.length?rows.map((a,i)=>{const l=a.nearest.line,s=a.nearest.substation,useLine=l&&(!s||l.distanceKm<=s.distanceKm),obj=useLine?l:s,props=useLine?l?.feature.props:s?.feature.props,kind=useLine?'Hat':'TM',assetName=props?.name||props?.ref||(useLine?'Adsız hat':'Adsız TM'),dw=a.downwindAssets||{lines:[],substations:[]},wind=a.wind?`${a.downwindAlignment?'doğrultuda':'çapraz/ters'} · ${U.round(a.wind.speed,0)} km/h<br><small>koridor: ${dw.lines.length} hat / ${dw.substations.length} TM</small>`:'—';return `<tr data-risk-index="${i}"><td><span class="riskBadge ${a.riskBand.level}">${a.riskScore} · ${U.escapeHtml(a.riskBand.label)}</span></td><td>${a.event.count} tespit</td><td>${this.val(a.event.maxFrp,1,' MW')}</td><td>${kind}<br><small>${U.escapeHtml(assetName)}</small></td><td>${this.val(obj?.distanceKm,2,' km')}</td><td>${U.escapeHtml(props?.voltage||props?.voltageGroup||'bilinmiyor')}</td><td>${wind}</td><td>${U.formatLocal(new Date(a.event.latestDetectedAt))}</td></tr>`;}).join(''):'<tr><td colspan="8">25 km içinde şebeke varlığına yaklaşan kümelenmiş FIRMS olayı yok.</td></tr>';
      body.querySelectorAll('tr[data-risk-index]').forEach(el=>el.addEventListener('click',()=>A.Events.emit('focusRisk',rows[Number(el.dataset.riskIndex)])));
    }
    renderExportSummary(state){document.getElementById('exportSummary').innerHTML=`<p><strong>FIRMS ham tespit:</strong> ${state.fireData?.length||0}</p><p><strong>Yangın olayı:</strong> ${state.fireEvents?.length||0}</p><p><strong>Etki analizi:</strong> ${state.fireImpacts?.length||0}</p><p><strong>Aktif duman:</strong> ${state.smokeVariable||'kapalı'} · ${state.smokeData?.filter(x=>x.value!=null).length||0} nokta</p><p><strong>Rüzgâr:</strong> ${state.windLevel||'10m'} · ${state.windData?.length||0} nokta</p><p><strong>Zaman:</strong> ${U.formatUtc(state.selectedTime)}</p>`;}
    renderAtmoHubDiscovery(r){const box=document.getElementById('atmoHubDiscoveryResult'),c=r?.candidates||[],v=r?.verified||[],errs=r?.errors||[],pages=r?.pages||[],assets=r?.assets||[];if(r?.reason==='SERVER_REQUIRED'){box.innerHTML='<strong>Sunucu modu gerekli / yapılandırılmamış.</strong><p><code>start_windows.bat</code> ile SUNUCU MODU açın. GitHub Pages yalnız statik dosya sunar; AtmoHub keşfi <code>/api/atmohub/discover</code> endpointini gerektirir.</p>';return;}const summary=`<div class="discoverySummary"><strong>Portal:</strong> ${U.escapeHtml(r?.portalStatus||'bilinmiyor')} · <strong>Sayfa:</strong> ${pages.length||r?.pagesScanned||0} · <strong>Varlık:</strong> ${assets.length||r?.assetsScanned||0} · <strong>Aday:</strong> ${c.length} · <strong>Doğrulanan:</strong> ${v.length}</div>`;const verified=v.length?`<p><strong>HTTP/içerik doğrulamasından geçen adaylar:</strong></p>${v.slice(0,12).map(x=>`<div class="candidateRow"><span class="badge analysis">${U.escapeHtml(x.kind||'DATA')}</span> <code>${U.escapeHtml(x.url||x)}</code><br><small>${U.escapeHtml(x.contentType||'')} · HTTP ${U.escapeHtml(x.status||'')} · CORS ${x.cors?'var':'yok/bilinmiyor'}</small></div>`).join('')}`:'<p><strong>Doğrulanmış public smoke/fire veri endpointi bulunamadı.</strong></p>';const candidates=c.length?`<details><summary>Keşfedilen adayları göster (${c.length})</summary>${c.slice(0,25).map(x=>{const u=typeof x==='string'?x:(x.url||x.raw||'');const kind=typeof x==='string'?'ADAY':(x.kind||'ADAY');return `<div class="candidateRow"><span class="badge forecast">${U.escapeHtml(kind)}</span> <code>${U.escapeHtml(u)}</code></div>`;}).join('')}</details>`:'';const errors=errs.length?`<details><summary>Tarama uyarıları (${errs.length})</summary>${errs.slice(0,15).map(e=>`<div class="sourceNote">${U.escapeHtml(typeof e==='string'?e:((e.url||'')+': '+(e.error||'')))}</div>`).join('')}</details>`:'';box.innerHTML=`${summary}${verified}${candidates}${errors}<p class="sourceNote">AtmoHub portalındaki orman yangını dumanı katmanı bilinse de, aday veri şeması/auth/CORS/kullanım koşulları doğrulanmadan uygulamada gerçek API olarak kullanılmaz. CAMS wildfire PM10 fallback aktif kalır.</p>`;}
  }
  A.UIManager=UIManager;
})(window.AtmoApp);
