// GridAtlas 3D v0.4 — src/ui/controls.js
// Faz 1: v0.3 tek dosyanin moduler karsiligi. Davranis korunur, gorsel degisiklik yok.
import { $, $$, normalize, toast, esc, clamp } from '../core/utils.js';
import { state, layers } from '../core/state.js';
import { ctx } from '../core/context.js';
import { get, searchAssets, voltageLevels, site } from '../data/station.js';
import { calculatePath, updateMeasurements } from '../electrical/electrical.js';
import { renderLayers } from './tree.js';
import { renderDetail, drawTrend, updateDetailValues } from './detail.js';
import { setLeftTab, initSidebarResize } from './sidebar.js';
import { emit, Events } from '../core/bus.js';
import { selectAsset, clearSelection, refreshVisuals } from '../scene/selection.js';
import { cameraPreset, focusAsset, orbit } from '../scene/scene.js';
import { toggleExploded, clearMeasure, clearZone, showZone, clearanceDemo } from '../features/tools.js';
import { commandSwitch } from '../features/training.js';
import { startReplay, demoScenario, updateReplayUI, normalOperation } from '../features/replay.js';
import { addEvent, events, replay } from '../features/events.js';
import { runSelfTests } from '../core/diagnostics.js';
import { updateWireVisibility, rebuildDebug } from '../scene/wires.js';

function resetView(){state.pan=false;const panButton=$('[data-action="pan"]');panButton.setAttribute("aria-checked","false");panButton.classList.remove("active");state.cutaway=false;state.flowP=true;state.flowQ=true;$('#flow-p').checked=true;$('#flow-q').checked=true;state.xray=false;state.exploded=false;state.explodeTarget=null;state.isolate=null;state.path=false;state.pathIds.clear();state.spread=false;state.voltage='all';state.phase='all';state.zone='none';state.measure=false;state.labels=true;state.analysis='none';state.terminals=false;state.connectivity=false;state.powerFlow=true;Object.keys(layers).forEach(k=>layers[k]=!['grounding','trenches','protection','measurements'].includes(k));if(state.mode==='analysis')layers.measurements=true;$('#analysis-layer').value='none';$('#power-flow').checked=true;$('#setting-terminals').checked=false;$('#setting-connectivity').checked=false;clearMeasure();clearZone();renderLayers();clearSelection();cameraPreset('iso');updateAnalysisLegend();refreshVisuals();}
// MODES AND CONTROLS
function setMode(mode){state.mode=mode;state.analysis=mode==='analysis'?$('#analysis-layer').value:'none';layers.measurements=mode==='analysis';$('#analysis-controls').classList.toggle('hidden',mode!=='analysis');$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});if(mode==='topology'){state.path=true;if(!state.selected)state.selected=get('LINE-400-01').assetId;calculatePath();}else state.path=false;renderLayers();renderDetail();emit(Events.MODE_CHANGED,{mode});updateAnalysisLegend();refreshVisuals();}
function updateAnalysisLegend(){const el=$('#analysis-legend'),on=state.mode==='analysis'&&state.analysis!=='none';el.classList.toggle('hidden',!on);if(on){$('#legend').open=true;el.innerHTML=state.analysis==='voltage'?'<b>GERİLİM · |U / Un − 1|</b><br>● ≤ %2.5 &nbsp; ● %2.5–5 &nbsp; ! > %5<br>Un: '+voltageLevels.join(' / ')+' kV':'<b>YÜKLENME · Ekipmanın DEMO anma değeri</b><br>● < %50 &nbsp; ● %50–80<br>● %80–100 &nbsp; ! > %100<br>Trafo: MVA · Şönt: Mvar · Diğer: A';}}
function panelToggle(side){if(innerWidth<=900){document.body.classList.toggle('mobile-'+side);document.body.classList.remove('mobile-'+(side==='left'?'right':'left'));return;}document.body.classList.toggle(side+'-collapsed');$('.panel-reopen.'+side).classList.toggle('hidden',!document.body.classList.contains(side+'-collapsed'));}
function dialog(id){const d=$('#'+id+'-dialog');if(d&&!d.open)d.showModal();}
async function screenshot(){if(!ctx.renderer){toast('PNG kaydetmek için 3D sahne gerekir.',true);return;}try{ctx.renderer.render(ctx.scene,ctx.camera);const blob=await new Promise(resolve=>ctx.canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG oluşturulamadı');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='GridAtlas-TM01-'+Date.now()+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('3D sahne PNG olarak kaydediliyor.');}catch(e){toast('Görüntü kaydedilemedi: '+e.message,true);}}
const actions={pan:()=>{state.pan=!state.pan;const b=$('[data-action="pan"]');b.setAttribute('aria-checked',String(state.pan));b.classList.toggle('active',state.pan);toast(state.pan?'Sürükleyerek kaydırma etkin.':'Sürükleyerek döndürme etkin.');},acknowledge:()=>{state.alarmAck=true;addEvent('normal','Alarm acknowledged · Alarm onaylandı','CB-401');toast('Alarm onaylandı. Elektriksel durum değişmedi.');},fit:()=>cameraPreset($('#camera-preset').value),top:()=>cameraPreset('top'),focus:()=>focusAsset(),reset:resetView,help:()=>dialog('help'),settings:()=>dialog('settings'),zones:()=>dialog('zones'),isolate:()=>{if(!state.selected)toast('Önce bir ekipman seçin.');else dialog('isolate');},energy:()=>{state.path=!state.path;if(state.path)calculatePath();refreshVisuals();},connectivity:()=>{state.path=!state.path;if(state.path)calculatePath();refreshVisuals();},xray:()=>{state.xray=!state.xray;refreshVisuals();},explode:()=>toggleExploded(),'explode-tr':()=>toggleExploded(true),'phase-spread':()=>{state.spread=!state.spread;refreshVisuals();},measure:()=>{state.measure=!state.measure;clearMeasure();if(state.measure){$('#measurement').innerHTML='Mesafe ölçümü · Sahnede iki nokta seçin.<small>Yalnız geometrik/demo ölçüm. ESC ile çıkın.</small>';$('#measurement').classList.remove('hidden');}if(ctx.canvas)ctx.canvas.style.cursor=state.measure?'crosshair':'grab';refreshVisuals();},clearance:clearanceDemo,labels:()=>{state.labels=!state.labels;refreshVisuals();},'zoom-in':()=>orbit.wantedRadius=clamp(orbit.wantedRadius*.8,12,site.maxRadius),'zoom-out':()=>orbit.wantedRadius=clamp(orbit.wantedRadius*1.2,12,site.maxRadius),screenshot,fullscreen:async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#app').requestFullscreen();}catch(e){toast('Bu tarayıcı tam ekran isteğine izin vermedi.',true);}},'left-panel':()=>panelToggle('left'),'right-panel':()=>panelToggle('right'),'bottom-min':()=>{document.body.classList.remove('bottom-expanded');document.body.classList.toggle('bottom-minimized');},'bottom-expand':()=>{document.body.classList.remove('bottom-minimized');document.body.classList.toggle('bottom-expanded');const ev=$('#events');if(ev&&document.body.classList.contains('bottom-expanded'))ev.scrollTop=ev.scrollHeight;},switch:()=>commandSwitch(),replay:startReplay,'replay-play':()=>{if(!replay.started||replay.time>=replay.duration)startReplay();else{replay.playing=!replay.playing;updateReplayUI();}},'replay-reset':()=>normalOperation(),'selftest':()=>runSelfTests()};
const icons={fit:'M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5M8 8h8v8H8z',ruler:'M3 15L15 3l6 6L9 21zM8 10l3 3M12 6l3 3M5 14l3 3',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6',reset:'M4 8a8 8 0 1 1 0 8M4 3v5h5',camera:'M3 7h5l2-3h4l2 3h5v13H3zM16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',fullscreen:'M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5',settings:'M9 3h6l1 4 4 1v7l-4 1-1 5H9l-1-5-4-1V8l4-1zM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',plus:'M12 5v14M5 12h14',minus:'M5 12h14',top:'M4 4h16v16H4zM4 10h16M10 4v16',spread:'M12 3v18M8 8l-4 4 4 4M4 12h6M16 8l4 4-4 4M14 12h6',label:'M3 4h18v13h-8l-5 4v-4H3zM7 8h10M7 12h6',path:'M3 5h7v7h11M3 19h7v-7M17 8l4 4-4 4',play:'M7 4l13 8-13 8z'};
function initUI(){
 $$('[data-icon]').forEach(b=>b.insertAdjacentHTML('afterbegin',`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[b.dataset.icon]}"/></svg>`));
 document.addEventListener('click',e=>{const button=e.target.closest('button,[role="button"]');if(!button)return;
  if(button.hasAttribute('data-close')){button.closest('dialog').close();return;}
  if(button.dataset.asset){selectAsset(button.dataset.asset);if(innerWidth<=900&&button.closest('#sld-panel'))document.body.classList.remove('mobile-left','mobile-right');return;}
  if(button.dataset.action){const action=actions[button.dataset.action];if(action){const result=action();if(result?.catch)result.catch(error=>toast(error.message,true));}if(button.closest('dialog')&&['replay'].includes(button.dataset.action))button.closest('dialog').close();return;}
  if(button.dataset.mode){setMode(button.dataset.mode);return;}
  if(button.dataset.voltage){state.voltage=button.dataset.voltage;refreshVisuals();return;}
  if(button.dataset.phase){state.phase=button.dataset.phase;refreshVisuals();return;}
  if(button.dataset.leftTab){setLeftTab(button.dataset.leftTab);return;}
  if(button.dataset.zone){showZone(button.dataset.zone);button.closest('dialog').close();return;}
  if(button.dataset.isolate){state.isolate=button.dataset.isolate==='none'?null:{scope:button.dataset.isolate,id:state.selected};button.closest('dialog').close();refreshVisuals();if(state.isolate)focusAsset();return;}
  if(button.dataset.metric){state.trend=button.dataset.metric;drawTrend();return;}
  if(button.dataset.demo){demoScenario(button.dataset.demo);button.closest('dialog').close();return;}
  if(button.dataset.event){const ev=events.find(x=>x.id===Number(button.dataset.event));if(ev)selectAsset(ev.assetId);return;}
 });
 document.addEventListener('change',e=>{const el=e.target;if(el.dataset.layer){layers[el.dataset.layer]=el.checked;if(el.dataset.layer==='protection')showZone(el.checked?'transformer':'none');refreshVisuals();}});
 $('#camera-preset').addEventListener('change',e=>cameraPreset(e.target.value));$('#analysis-layer').addEventListener('change',e=>{state.analysis=e.target.value;updateAnalysisLegend();refreshVisuals();});$('#power-flow').addEventListener('change',e=>{state.powerFlow=e.target.checked;refreshVisuals();});
 $('#replay-speed').addEventListener('change',e=>replay.speed=Number(e.target.value));
 for(const [key,id] of [['terminals','setting-terminals'],['connectivity','setting-connectivity']])$('#'+id).addEventListener('change',e=>{state[key]=e.target.checked;rebuildDebug();});
 $('#setting-quality').addEventListener('change',e=>{state.quality=e.target.checked;updateMeasurements(true);updateDetailValues();addEvent('warning','Data Quality Demo '+(state.quality?'ON':'OFF'),'CVT-401');});
 $('#setting-shadows').addEventListener('change',e=>{state.shadows=e.target.checked;if(ctx.renderer){ctx.renderer.shadowMap.enabled=state.shadows;ctx.renderer.shadowMap.needsUpdate=true;}});
 $('#search').addEventListener('input',e=>{const q=normalize(e.target.value.trim());$('#search-results').classList.toggle('hidden',!q);if(!q)return;const results=searchAssets(q);$('#search-results').innerHTML=results.length?results.slice(0,30).map(a=>`<button role="option" data-asset="${a.assetId}"><span>${esc(a.name)}</span><span class="muted mono">${esc(a.tag)}</span></button>`).join(''):'<p class="muted" style="padding:14px">Eşleşen ekipman bulunamadı.</p>';});
 $('#search-results').addEventListener('click',()=>{$('#search-results').classList.add('hidden');$('#search').value='';});
 $('#search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();$('#search-results button')?.focus();}if(e.key==='Enter'){const first=$('#search-results button');if(first)first.click();}});
 document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#search-results').classList.add('hidden');});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('dialog[open]'))return;$('#search-results').classList.add('hidden');state.isolate=null;state.measure=false;state.path=false;clearMeasure();clearSelection();return;}if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('dialog[open]'))return;const key=e.key.toLowerCase();const map={f:'focus',i:'isolate',x:'xray',e:'explode',r:'reset','?':'help'};if(map[key]){e.preventDefault();actions[map[key]]();}else if(['1','2','3'].includes(key)){cameraPreset({'1':'perspective','2':'top','3':'iso'}[key]);}if((e.key==='Enter'||e.key===' ')&&e.target.matches('#sld .asset')){e.preventDefault();selectAsset(e.target.dataset.asset);}});
 $$('button').forEach(b=>{if(!b.title)b.title=b.textContent.trim();if(!b.hasAttribute('aria-label'))b.setAttribute('aria-label',b.title);});
 const observer=new MutationObserver(records=>{for(const record of records)for(const added of record.addedNodes)if(added.nodeType===1){const buttons=added.matches('button')?[added,...added.querySelectorAll('button')]:[...added.querySelectorAll('button')];buttons.forEach(b=>{if(!b.title)b.title=b.textContent.trim();if(!b.hasAttribute('aria-label'))b.setAttribute('aria-label',b.title);});}});observer.observe($('#app'),{childList:true,subtree:true});initSidebarResize();
}
function prepareV02UI(){
 $('#scene-subtitle').textContent='4 × 400 kV Hat → 2 Ototrafo → 6 × 154 kV Hat · 3 Güç Trafosu → 33 kV';$('.scene-heading h2').textContent='Üç gerilim. Tek merkez.';$('.site-label span:last-child').textContent='400 / 154 / 33 kV';$('.scene-top-right .tiny-group').innerHTML='<button data-voltage="all" class="active">Tümü</button>'+voltageLevels.map(k=>`<button data-voltage="${k}">${k} kV</button>`).join('');
 $('#status-154').insertAdjacentHTML('afterend','<span id="status-33" class="status-live"></span>');$('.quick-tools').insertAdjacentHTML('beforeend','<button data-action="cutaway" title="Kumanda ve OG Kabin Kesiti">Kabin kesiti</button>');$('#analysis-controls').insertAdjacentHTML('beforeend','<label><input type="checkbox" id="flow-p" checked>P</label><label><input type="checkbox" id="flow-q" checked>Q</label>');$('#legend .legend-body').insertAdjacentHTML('afterbegin','<div class="flow-legend"><span>● Aktif güç P</span><span style="color:#dcc19a">◯ Reaktif güç Q</span><small>Dengeli DEMO akış · Elektron hareketi değildir.</small></div>');$('#settings-dialog .demo-grid').insertAdjacentHTML('beforeend','<button data-demo="reverse">⇄ Ters Aktif Güç</button>');$('#settings-dialog .architecture').insertAdjacentHTML('afterend','<p class="muted">P ve Q; dört kaynaklı terminal ağında dengeli DEMO dağılımıdır. Paralel ototrafolar beslemeyi paylaşır. AC yük akışı, koruma koordinasyonu veya saha tasarım hesabı değildir. Gerçek tesis anma verisi kullanılmaz.</p>');

 $('#selftest-results').insertAdjacentHTML('afterend','<details class="validation-details"><summary>Model sayımları ve render bilgisi</summary><pre id="validation-stats" class="validation-stats"></pre></details>');actions.cutaway=()=>{state.cutaway=!state.cutaway;refreshVisuals();};for(const [id,key] of [['flow-p','flowP'],['flow-q','flowQ']])$('#'+id).addEventListener('change',e=>{state[key]=e.target.checked;updateWireVisibility();});document.title='GRIDATLAS 3D v0.6 | 400 / 154 / 33 kV';
}

export { resetView, setMode, updateAnalysisLegend, panelToggle, dialog, screenshot, actions, icons, initUI, prepareV02UI };
